author: Kathrin Gruber
permalink: pretty
paginate: 5
title: Introduction to R
description: Programming with R for FAECTOR
theme: jekyll-theme-minimal

docs:
  - title: Getting Started
    children:
      - title: "A primer on R (and R Studio)"
        url: 
