author: Kathrin Gruber
permalink: pretty
paginate: 5
title: Introduction to R
description: Introduction to programming with R for FAECTOR
show_downloads: true
google_analytics:

theme: jekyll-theme-minimal

plugins:
  - jekyll-sitemap
