name: R Introduction
permalink: pretty
theme: minima

lsi: false
 safe: true
 source: [RIntroduction]
 incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
