author: Kathrin Gruber
permalink: pretty
paginate: 5
title: Introduction to programming with R for FAECTOR
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:

theme: jekyll-theme-minimal

plugins:
  - jekyll-sitemap
